# Use rootmysql as userpassword credentials
version: '3'
services:
  mysql:
    image: mysql:8.0.20
    command:
            --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=jcjajplae*88
    volumes:
      - /home/ubuntu/database/mysql:/var/lib/mysql

  www:
    image: www
    ports:
      - 38980:80
    cpus: 1
    mem_limit: 512m
    environment:
      - "APACHE_HTTPD_CORS=On"
      - "APACHE_HTTPD_CORS_ALLOW_ORIGIN=*"

  api:
    image: api
    ports:
      - 8083:8080
    cpus: 1
    mem_limit: 512m
